services:
  math-questions-api:
    name: math-questions-api-1
    image: registry.saeidnia.com/math-questions-api:latest
    ports:
      - 5000:5000
    networks:
          - pangolin
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

networks:
  pangolin:
    external: true
