name: Build docker container

on:
  workflow_dispatch:
  
  push:
    branches:
      - "main"

env:
  DOCKER_IMAGE_NAME: math-question-api
  DOCKER_REGISTRY_URL: registry.saeidnia.com

jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get short commit hash
        id: git_short_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Create tag
        id: create_tag
        run: |
          git tag v${{ steps.git_short_hash.outputs.hash }}
          git push origin v${{ steps.git_short_hash.outputs.hash }}
      
      - name: Get tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and Push the Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
    